# Generated by Django 4.2.27 on 2026-01-18 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=200)),
                ('aforo', models.PositiveIntegerField()),
                ('lugar', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('descripcion_evento', models.TextField()),
                ('imaxe_evento', models.ImageField(upload_to='eventos/')),
                ('data_evento', models.DateTimeField()),
                ('localizacion', models.CharField(max_length=200)),
                ('prezo_evento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entradas_vendidas', models.PositiveIntegerField(default=0)),
                ('data_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.sala')),
            ],
        ),
    ]
