# Generated by Django 4.2.27 on 2026-02-05 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='entradas_vendidas',
            new_name='entradas_venta',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='sala',
            new_name='tipo_localizacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='condiciones_confirmacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_iban',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='prezo_evento',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
