# Generated by Django 4.2.27 on 2026-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_entradas_vendidas_evento_entradas_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='numero_iban',
            field=models.CharField(max_length=34),
        ),
    ]
