# Generated by Django 4.2.27 on 2026-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_prezo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='prezo_evento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
