# Generated by Django 4.2.27 on 2026-02-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_prezo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='numero_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
