# Generated by Django 4.2.27 on 2026-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_numero_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_localizacion',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
