# Generated by Django 4.2.27 on 2026-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_evento_tipo_localizacion_delete_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_localizacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
