# Generated by Django 4.2.27 on 2026-02-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_evento_tipo_localizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imaxe_evento',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='localizacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
