# Generated by Django 4.2.27 on 2026-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_imaxe_evento_alter_evento_localizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='entradas_reservadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='entradas_vendidas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
