# Generated by Django 4.2.27 on 2026-02-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0010_evento_entradas_reservadas_evento_entradas_vendidas"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservaButaca",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zona", models.CharField(max_length=20)),
                ("fila", models.PositiveIntegerField()),
                ("butaca", models.PositiveIntegerField()),
                ("data_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_butacas",
                        to="eventos.evento",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reservabutaca",
            constraint=models.UniqueConstraint(
                fields=("evento", "zona", "fila", "butaca"),
                name="unique_reserva_butaca",
            ),
        ),
    ]
