# Generated by Django 4.2.27 on 2026-02-27 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0011_reserva_butaca"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservabutaca",
            name="organizador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_butacas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
