# Generated by Django 4.2.27 on 2026-02-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_reservabutaca_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='xustificacion_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
