# Generated by Django 4.2.27 on 2026-03-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0014_reservabutaca_email_reservabutaca_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservabutaca',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_butacas', to=settings.AUTH_USER_MODEL),
        ),
    ]
