# Generated by Django 4.2.27 on 2026-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_reservabutaca_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_gestion_entrada',
            field=models.CharField(blank=True, choices=[('pagina', 'Xestionado a través da páxina'), ('manual', 'Xestionado polo organizador'), ('gratis', 'Evento gratuíto')], max_length=20, null=True),
        ),
    ]
