# Generated by Django 4.2.27 on 2026-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_evento_tipo_gestion_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='procedimiento_cobro_manual',
            field=models.TextField(blank=True, null=True),
        ),
    ]
