# Generated by Django 4.2 on 2026-03-23
from django.db import migrations, models
import random
import string

def generate_codigo_validacion(apps, schema_editor):
    ReservaButaca = apps.get_model('eventos', 'ReservaButaca')
    for reserva in ReservaButaca.objects.all():
        if not reserva.codigo_validacion:
            letras = ''.join(random.choices(string.ascii_uppercase, k=3))
            reserva.codigo_validacion = f"{reserva.id}-{letras}"
            reserva.save()

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_evento_nota_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabutaca',
            name='codigo_validacion',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.RunPython(generate_codigo_validacion, reverse_code=migrations.RunPython.noop),
    ]
