# Generated by Django 4.2.27 on 2026-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_reservabutaca_codigo_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nota_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
