# Generated by Django 4.2.27 on 2026-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_evento_prezo_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='prezo_pvp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='zonaprezo',
            name='prezo_pvp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
