# Generated by Django 4.2.27 on 2026-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0034_evento_prezo_pvp_zonaprezo_prezo_pvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonaprezo',
            name='prezo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
