[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "postgresql"]

providers = ["python"]

[phases.install]
cmds = ["python -m pip install -r BACKEND/requirements.txt"]

[start]
cmd = "cd BACKEND && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn BACKEND.wsgi --bind 0.0.0.0:$PORT"
