# Generated by Django 4.2.27 on 2026-01-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='notificaciones',
        ),
        migrations.RemoveField(
            model_name='organizador',
            name='pagina_web',
        ),
    ]
