# Generated by Django 4.2.27 on 2026-01-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_remove_organizador_notificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='foto_organizador',
            field=models.ImageField(upload_to='fotos_organizador'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='nombre_organizador',
            field=models.CharField(max_length=100),
        ),
    ]
