# Generated by Django 4.2.27 on 2026-01-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0003_alter_organizador_foto_organizador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='nombre_organizador',
        ),
    ]
