# Generated by Django 4.2.27 on 2026-01-21 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0004_remove_organizador_nombre_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='nome_organizador',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizador',
            name='foto_organizador',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_organizador'),
        ),
    ]
