# Generated by Django 4.2.27 on 2026-01-26 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0005_organizador_nome_organizador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{5,20}$', message='Teléfono inválido')]),
        ),
    ]
