# Generated by Django 4.2.27 on 2026-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0006_alter_organizador_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(choices=[('ES', 'España'), ('PT', 'Portugal')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('auditorio', 'Auditorio'), ('teatro', 'Teatro'), ('pabellon', 'Pabellón'), ('bar', 'Bar'), ('restaurante', 'Restaurante'), ('universidade', 'Universidade'), ('instituto', 'Instituto'), ('praza', 'Praza'), ('centro_cultural', 'Centro Cultural'), ('recinto_privado', 'Recinto Privado')], max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('fonte', models.CharField(default='OSM', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
