# Generated by Django 4.2.27 on 2026-02-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0007_lugar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
