# Generated by Django 4.2.27 on 2026-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0008_delete_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='idioma',
            field=models.CharField(default='galego', max_length=50),
        ),
        migrations.AddField(
            model_name='organizador',
            name='numero_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
